linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  goimports:
    local-prefixes: github.com/gox-framework/gox
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - forbidigo
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - goerr113
    - maligned
    - nestif
    - testpackage
    - wsl

run:
  skip-dirs:
    - examples
    - dist
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
    - path: cmd/
      linters:
        - gochecknoglobals
    - linters:
        - golint
      text: "should have a package comment"

  fix: true

severity:
  default-severity: warning

service:
  golangci-lint-version: 1.54.x